### ISSUE TITLE
POM <parent> element

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guide-rest-intro#30]
Should this (and other early guides) `pom.xml` be updated to use the following `<parent>` section like the Maven guide (https://github.com/OpenLiberty/guide-maven-intro/blob/master/finish/pom.xml) does?

```
<parent>
        <groupId>net.wasdev.wlp.maven.parent</groupId>
        <artifactId>liberty-maven-app-parent</artifactId>
        <version>2.0</version>
</parent>
```

(I think the Liberty Maven plugin was updated after the first guide(s) were published. I'm not sure if anything else is different or what the impact is beyond best practice.)

**Comment by lauracowen** [comment]
I guess one reason to do the update is the problem I'm finding: I copied the Rest guide's app and I'm adapting it to another. I want to know what some of the pom.xml settings are but it's set up differently from the pom.xml in the Maven guide (which otherwise is useful in explaining all the pom.xml sections). So the two POMs don't map properly, making it harder to use the info in the Maven guide.

**Comment by andrewdes** [comment]
@lauracowen One of the issues with doing this is that all the goals from the liberty-maven-app-parent will get ran even though certain goals may be inapplicable to specific guides.

For example, guides that do not have tests (such as rest-client-angularjs), will have the server started before the pre-integration-test phase and stopped afterwards. But, since there are no tests, the server is just being started and stopped unnecessarily and just adding time to the build.

**Comment by lauracowen** [comment]
Hmm... @gcharters  what do you think?

**Comment by evelinec** [comment]
Tagging @gkwan-ibm to this issue.

**Comment by gkwan-ibm** [comment]
@andrewdes Do you have other example/reason?

In your example, for the guides have no tests, it is still worth to run start and stop server to confirm that the installed wlp and server have no problem.

**Comment by andrewdes** [comment]
@gkwan-ibm I guess another example would be the `stop-server` goal being ran in the pre-clean phase.
In most guides, generally the only time the clean phase is executed is at the start of the guide when instructed to run `mvn clean install`, so the server shouldn't be running in the first place. So once again, this is just adding time to the build.

**Comment by gkwan-ibm** [comment]
- Tried to RestIntro, JWT, JPA
- will try KubeIntro
- Doc the pros and cons

**Comment by andrewdes** [comment]
Applied the changes to the following guides:
- Rest Intro
- JWT
- JPA

**Pros of using <parent> element in the POM:**
- Eliminates (or significantly reduces) code in the `<exections />` section of the liberty-maven-plugin, thus, simplifying the POM file(s) in the guides.
- More consistency between the guides (In terms of the code, as well as the maven goals being executed). For example, right now the Rest-intro guide runs the `install-apps` goal during the `pre-integration-test` phase and the JWT guide runs that same goal during the `package` phase.
- As Laura mentioned above, POM file would map to the POM file in the Maven guide making the information in the Maven guide more useful.

**Cons of using <parent> element in the POM:**
- Runs goals mentioned here: https://github.com/WASdev/ci.maven/blob/master/docs/parent-pom.md even though certain goals might not be necessary in certain scenarios. For example, on the JWT guide using the parent POM introduces the execution of: `stop-server`, `install-feature` and `package-server`. Though, this may vary from guide to guide.
- Less obvious what `liberty-maven-plugin` goals are being ran and during what phase when looking at the guides POM file (since you would have to navigate to the parent POM).

**Comment by andrewdes** [comment]
We have decided to make this change and use the liberty-maven-app-parent. All guides will be updated while converting to new multi-pane layout.
