### ISSUE TITLE
General User Feedback and Multipane Issues

### ISSUE THREAD

**Issue by Rachelwrq** [OpenLiberty/guide-rest-intro#57]
## General Feedback
- [x] Minor grammar issues in multiple sections
- [x] In **What you'll learn** section: second last paragraph needs more modification in terms of wording.
- [x] "GET" request in **What you'll learn** should be in backticks 

### General Issues
- [x] Change instructions in action arrows
- [x] Hotspots need to be adjusted accordingly in multiple sections
- [x] Update POM files
- [x] Update .travis.yaml file
- [x] Check the format of files

#### Creating a JAX-RS resource
- [x] Would it be more helpful if the SystemApplication.java file is also ready for display and have corresponding hotspots for users’ convenience?

#### Configuring the server
- [x] Some grey text of code snippets for the POM file should be presented at the right pane.

#### Testing the service
- [x] Some grey text of code snippets should be deleted since the same code can be presented at the right pane 
- [x] “run the command `mvn install`” right now is not in the correct format

#### Guide Attribution
- [x] This section is messed up on the multipane branch right now.

**Comment by justineechen** [comment]
- [ ] Remove `server.xml` from `start/` directory and change "Edit the server configuration file.." to "Create the server configuration file" in `Configuring the server` 

- [ ] IMO the first hotspot to `pom.xml` is not necessary because there is a specific reference to the file at the end of the paragraph, this hotspot that switches the files is distracting for the user:
<img width="586" alt="screen shot 2018-12-18 at 1 36 43 pm" src="https://user-images.githubusercontent.com/18709242/50175158-11651f80-02ca-11e9-91c3-43df19c54792.png">

- [ ] In `Testing the service`, remove "Open the `pom.xml`.." since it is already open for the users in the right hand panel

- [ ] At the beginning of `Creating a JAX-RS application`, add a line asking users to navigate to the start directory 

- [ ] After hitting `http://localhost:9080/LibertyProject/System/properties` in `Testing the service`, I got Context Root Not found

- [ ] `http://localhost:9080/LibertyProject/System/properties` in `Testing the service` should be a clickable link

- [ ] Tests fail in `mvn install`

**Comment by justineechen** [comment]
### Checklist for multipane conversion
**Through the browser:**
- [ ] Read over guide and run through all commands (copy and paste using browser etc..)
- [ ] Test the actual application (use it, hit endpoints, etc.)
- [ ] No files in the middle panel (guide section)
- [ ] Appropriate files are being displayed on the right hand side at the right time
- [ ] Any mention of code in the right panel should be hot spotted
- [ ] Make sure hotspots actually point to the correct lines
- [ ] Any actions to the code (Create, replace) should be put in an arrow (code_command)
- [ ] All code commands are highlighting the right code
- [ ] Any actions to look at the code should be a hotspot
- [ ] Guide attribution is present

**In the README.adoc:**
- [ ] Tags in the front matter are correct
     - [ ] If `:page-guide-category: none` remove `:page-essential:` and `:page-essential-order:`

**In other files:**
- [ ] Failsafe plugin and Surefire plugin updates if applicable
- [ ] Parent POM update
     - [ ] start directory
     - [ ] finish directory
- [ ] Files are formatted correctly
- [ ] .travis.yaml file is updated accordingly

**Comment by justineechen** [comment]
### Checklist for Post-Review
**Through the browser:**
- [ ] Read through guide, making sure that the flow of the guide is good
- [ ] Click all links to make sure they lead to the correct place
- [ ] Make sure hotspots, code_commands and files are correct
- [ ] Run Acrolinx

**Comment by justineechen** [comment]
This guide has successfully been converted to multipane and has no blockers.
