### ISSUE TITLE
Context Root of `LibertyProject` is not used due to loose config issue

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/guide-rest-intro#67]
When running through this guide, the server used `rest` as the context root for the application rather than the expected `LibertyProject`.  I believe this is because the app is installed using loose config - so the target's dropins directory contains `rest.war.xml`, but the server.xml file specifies that `rest.war` should use the contextRoot specified in the system property.  

When I changed the server.xml to file from `rest.war` to `rest.war.xml`, everything worked as expected for me.  Without that change, I get 404s when attempting to access the system property endpoint.

**Comment by yeekangc** [comment]
@gkwan-ibm

**Comment by gkwan-ibm** [comment]
@andymc12 which version of open liberty?

**Comment by andymc12** [comment]
@gkwan-ibm - 19.0.0.2 - that was the version downloaded when I ran the pom.xml file from the guide.

**Comment by andymc12** [comment]
I ran the sample again, using `mvn clean install liberty:run-server` and this time it worked.  One difference I noticed between the failing case and the working case was _where_ the rest.war.xml file was deployed.  If it was deployed to the `dropins` directory, then it failed.  If it was deployed to the `apps` directory, then it worked.  I confirmed this behavior when I manually moved the file from `apps` to `dropins`. 

The strangeness is that it first deployed to `dropins`.  I believe the correct behavior for this sample is to always deploy to `apps`.  Maybe there was something wrong with the liberty plugin?  I didn't see `apps` or `dropins` in the pom.xml - so maybe it is non-deterministic where the app gets deployed if neither is specified?  In any case, I don't think this is a high priority issue now that I understand it better.

Thanks, Andy

**Comment by gkwan-ibm** [comment]
The guide was recently updated to use Liberty Maven plugin development mode. The flow is different than before. Now, the application should be deployed to the `apps` directory. When running the guide at the start directory, it is expected that the context root is not `LibertyProject` because of loose config. When readers running into the section "Configuring the server", they will configure the server including the context root. After updating the server.xml, the application can be accessed the service through the context root `LibertyProject`. If before updating the server.xml, the context root should be `guide-rest-intro`.

@andymc12, I am closing this issue. If you still have concern, you may reopen this issue.
